name: Discord.js Bot CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
          envkey_DEV_TOKEN_2: "796428644783489024"
          envkey_DATABASE_URI: "mongodb://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@goodloss.fr:27017/beta"
          envkey_DEV_GUILD: "948895533353824257"
          envkey_LEADERBOARD_API_TOKEN: ${{ secrets.LEADERBOARD_API_TOKEN }}
          envkey_HOST_URL: "goodloss.fr"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: node medbot.js
        timeout-minutes: 1

      - name: Deploy to server
        if: success()
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create SSH key file
        if: success()
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Update and restart bots on server
        if: success()
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/ubuntu/apps/MedBot
            git pull origin master
            ./restartBot
          
            cd /home/ubuntu/apps/OrianaBot
            git pull origin master
            ./restartBot
          EOF